from pathlib import Path
import re
p=Path('index.html'); s=p.read_text(encoding='utf-8')
VER='2026-09-12-0205'
s=re.sub(r"const APP_VERSAO_ATUAL = '[^']+';", f"const APP_VERSAO_ATUAL = '{VER}';", s, count=1)
css='''\n  .gfc-multi-btn{width:100%;box-sizing:border-box;padding:5px 4px;border-radius:8px;border:1.5px solid #D8DAE0;background:#fff;color:#9CA3AF;text-align:center;font-family:'Baloo 2',sans-serif;font-weight:700;font-size:11.5px;line-height:normal;cursor:pointer;}\n  .gfc-multi-btn.tem-valores{background:#F3E8FF;border-color:#A21CAF;color:#4C1D95;}\n  .gfc-multi-inline{grid-column:1/-1;display:none;background:#fff;border:1.5px solid #A21CAF;border-radius:10px;padding:8px;margin-top:2px;}\n  .gfc-multi-inline.show{display:block;}\n  .gfc-multi-title{font-family:'Baloo 2',sans-serif;font-size:11px;font-weight:800;color:#7E22CE;margin-bottom:6px;}\n  .gfc-multi-options{display:flex;flex-wrap:wrap;gap:5px;justify-content:center;}\n  .gfc-multi-option{min-width:30px;height:30px;padding:0 7px;border-radius:7px;border:1.5px solid #D8DAE0;background:#fff;color:#4C1D95;font-family:'Baloo 2',sans-serif;font-size:9.5px;font-weight:800;}\n  .gfc-multi-option.on{background:#A21CAF;border-color:#A21CAF;color:#fff;}\n'''
if '.gfc-multi-btn{' not in s:s=s.replace('  .gfc-fixas-btn{',css+'  .gfc-fixas-btn{',1)
fields=[('Pares','gfcFiltroPares'),('Ímpares','gfcFiltroImpares'),('Primos','gfcFiltroPrimos'),('Fibonacci','gfcFiltroFib'),('Moldura','gfcFiltroMoldura'),('Centro','gfcFiltroCentro'),('Múlt. de 3','gfcFiltroMult3')]
for label,id in fields:
 pat=rf'<div class="gfc-dark-input-wrap">\s*<input type="number" inputmode="numeric" id="{id}" placeholder=" ">\s*<span>{re.escape(label)}</span>\s*</div>';rep=f'<div class="gfc-dark-input-wrap"><button type="button" id="{id}" class="gfc-multi-btn" data-label="{label}">{label}</button></div>';s,n=re.subn(pat,rep,s,count=1)
 if n!=1:raise SystemExit('markup '+id)
needle='          <div class="gfc-fixas-inline" id="gfcFixasInline">'
picker='''          <div class="gfc-multi-inline" id="gfcMultiInline">\n            <div class="gfc-multi-title" id="gfcMultiTitle">Escolha as quantidades</div>\n            <div class="gfc-multi-options" id="gfcMultiOptions"></div>\n            <div class="gfc-fixas-inline-actions"><div class="conf-count">Selecionadas: <strong id="gfcMultiCount">0</strong></div><div style="display:flex;gap:6px;"><button type="button" class="btn-cancel" id="gfcMultiLimpar">LIMPAR</button><button type="button" class="btn-confirm" id="gfcMultiOk">OK</button></div></div>\n          </div>\n'''
if 'id="gfcMultiInline"' not in s:s=s.replace(needle,picker+needle,1)
js='''\nconst GFC_MULTI_IDS=['gfcFiltroPares','gfcFiltroImpares','gfcFiltroPrimos','gfcFiltroFib','gfcFiltroMoldura','gfcFiltroCentro','gfcFiltroMult3'];\nconst gfcMultiSelecionados=Object.fromEntries(GFC_MULTI_IDS.map(id=>[id,new Set()]));let gfcMultiAtual=null;\nfunction gfcOpcoesFiltro(id){if(geradorGameAtual?.code==='LF')return ({gfcFiltroPares:[6,8,10,12],gfcFiltroImpares:[5,7,9,11,13],gfcFiltroPrimos:[3,5,7,9],gfcFiltroFib:[3,5,7],gfcFiltroMoldura:[8,10,12,14,16],gfcFiltroCentro:[3,5,7,9],gfcFiltroMult3:[2,4,6,8]})[id]||[];const k=gfc.dezenas||0;return Array.from({length:k+1},(_,i)=>i);}\nfunction gfcAtualizarMultiBotao(id){const el=document.getElementById(id),set=gfcMultiSelecionados[id];if(!el||!set)return;const label=el.dataset.label||'',vals=[...set].sort((a,b)=>a-b);el.textContent=vals.length?`${label} (${vals.join(' / ')})`:label;el.value=vals.join(',');el.classList.toggle('tem-valores',!!vals.length);}\nfunction gfcRenderMulti(){const box=document.getElementById('gfcMultiOptions'),title=document.getElementById('gfcMultiTitle'),count=document.getElementById('gfcMultiCount');if(!box||!gfcMultiAtual)return;const el=document.getElementById(gfcMultiAtual),set=gfcMultiSelecionados[gfcMultiAtual];title.textContent=`Escolha as quantidades de ${el.dataset.label}`;box.innerHTML='';gfcOpcoesFiltro(gfcMultiAtual).forEach(v=>{const b=document.createElement('button');b.type='button';b.className='gfc-multi-option'+(set.has(v)?' on':'');b.textContent=v;b.onclick=()=>{set.has(v)?set.delete(v):set.add(v);gfcAtualizarMultiBotao(gfcMultiAtual);gfcRenderMulti();};box.appendChild(b);});count.textContent=set.size;}\nfunction gfcAbrirMulti(id){gfcMultiAtual=id;gfcRenderMulti();document.getElementById('gfcFixasInline')?.classList.remove('show');document.getElementById('gfcMultiInline')?.classList.add('show');}\nGFC_MULTI_IDS.forEach(id=>document.getElementById(id)?.addEventListener('click',()=>gfcAbrirMulti(id)));document.getElementById('gfcMultiOk')?.addEventListener('click',()=>{document.getElementById('gfcMultiInline')?.classList.remove('show');gfcValidarFiltrosInstantaneo();});document.getElementById('gfcMultiLimpar')?.addEventListener('click',()=>{if(!gfcMultiAtual)return;gfcMultiSelecionados[gfcMultiAtual].clear();gfcAtualizarMultiBotao(gfcMultiAtual);gfcRenderMulti();gfcValidarFiltrosInstantaneo();});\nfunction gfcFiltroValores(id){const a=[...(gfcMultiSelecionados[id]||[])];return a.length?a:null;}function gfcAceitaFiltro(filtro,valor){return filtro===null||filtro===undefined||(Array.isArray(filtro)?filtro.includes(valor):filtro===valor);}\n'''
anchor='let gfcFixasSelecionadas = new Set();\n'
if 'const GFC_MULTI_IDS=' not in s:s=s.replace(anchor,anchor+js,1)
old="""  gfcFixasSelecionadas.clear();\n  ['gfcFiltroPares','gfcFiltroImpares','gfcFiltroPrimos','gfcFiltroFib','gfcFiltroMoldura','gfcFiltroCentro','gfcFiltroFixas','gfcFiltroMult3','gfcFiltroSoma'].forEach(id=>{\n    const el = document.getElementById(id);\n    if(el) el.value = '';\n  });""";new="""  gfcFixasSelecionadas.clear();\n  GFC_MULTI_IDS.forEach(id=>{ gfcMultiSelecionados[id].clear(); gfcAtualizarMultiBotao(id); });\n  const somaEl=document.getElementById('gfcFiltroSoma'); if(somaEl) somaEl.value='';\n  document.getElementById('gfcMultiInline')?.classList.remove('show');"""
if old not in s:raise SystemExit('init');s=s.replace(old,new,1)
for var,count in [('filtroPares','pares'),('filtroImpares','impares'),('filtroPrimos','primos'),('filtroFib','fib'),('filtroMoldura','moldura'),('filtroCentro','centro'),('filtroMult3','mult3')]:s=s.replace(f"if({var}!==null && {count}!=={var}) continue;",f"if(!gfcAceitaFiltro({var}, {count})) continue;",1)
old="""  const parseFiltro = id => {\n    const v = document.getElementById(id).value;\n    return v==='' ? null : gfcClamp(parseInt(v,10), 0, dezenasPorJogo);\n  };\n  const filtroPares = parseFiltro('gfcFiltroPares');\n  const filtroImpares = parseFiltro('gfcFiltroImpares');\n  const filtroPrimos = parseFiltro('gfcFiltroPrimos');\n  const filtroFib = parseFiltro('gfcFiltroFib');\n  const filtroMoldura = parseFiltro('gfcFiltroMoldura');\n  const filtroCentro = parseFiltro('gfcFiltroCentro');\n  const filtroMult3 = parseFiltro('gfcFiltroMult3');""";new="""  const filtroPares = gfcFiltroValores('gfcFiltroPares');\n  const filtroImpares = gfcFiltroValores('gfcFiltroImpares');\n  const filtroPrimos = gfcFiltroValores('gfcFiltroPrimos');\n  const filtroFib = gfcFiltroValores('gfcFiltroFib');\n  const filtroMoldura = gfcFiltroValores('gfcFiltroMoldura');\n  const filtroCentro = gfcFiltroValores('gfcFiltroCentro');\n  const filtroMult3 = gfcFiltroValores('gfcFiltroMult3');"""
if old not in s:raise SystemExit('parse');s=s.replace(old,new,1)
s=s.replace("if(filtroPares!==null && filtroImpares!==null && filtroPares + filtroImpares !== dezenasPorJogo){","if(filtroPares!==null && filtroImpares!==null && !filtroPares.some(p=>filtroImpares.some(i=>p+i===dezenasPorJogo))){",1)
start=s.index('function gfcValidarFiltrosInstantaneo(){');end=s.index("\n}\n\n['gfcFiltroPares'",start)+2;block=s[start:end]
block=re.sub(r"const ler = id => \{.*?\};\n  const v = \{.*?\n  \};","const ler=id=>GFC_MULTI_IDS.includes(id)?gfcFiltroValores(id):(()=>{const el=els[id];if(!el||el.value==='')return null;const n=parseInt(el.value,10);return Number.isFinite(n)?n:null;})();\n  const v = {pares:ler('gfcFiltroPares'), impares:ler('gfcFiltroImpares'), primos:ler('gfcFiltroPrimos'), fib:ler('gfcFiltroFib'), moldura:ler('gfcFiltroMoldura'), centro:ler('gfcFiltroCentro'), mult3:ler('gfcFiltroMult3'), soma:ler('gfcFiltroSoma')};",block,count=1,flags=re.S)
block=block.replace("if(val<minimo || val>maximo) marcar(id,`${label} precisa ficar entre ${minimo} e ${maximo}.`);","const vals=Array.isArray(val)?val:[val]; if(!vals.some(x=>x>=minimo&&x<=maximo)) marcar(id,`${label} precisa ter pelo menos uma opção entre ${minimo} e ${maximo}.`);").replace("if(v.pares!==null && v.impares!==null && v.pares+v.impares!==k){","if(v.pares!==null && v.impares!==null && !v.pares.some(p=>v.impares.some(i=>p+i===k))){").replace("if(v.moldura!==null && v.centro!==null && v.moldura+v.centro!==k){","if(v.moldura!==null && v.centro!==null && !v.moldura.some(m=>v.centro.some(c=>m+c===k))){")
s=s[:start]+block+s[end:]
s=s.replace("function gfcAbrirFixas(){\n  if(!geradorGameAtual) return;","function gfcAbrirFixas(){\n  if(!geradorGameAtual) return;\n  document.getElementById('gfcMultiInline')?.classList.remove('show');",1)
p.write_text(s,encoding='utf-8')
sw=Path('sw.js');t=sw.read_text(encoding='utf-8');t=re.sub(r"const CACHE_NAME = 'thor-loterias-[^']+';",f"const CACHE_NAME = 'thor-loterias-{VER}';",t,count=1);sw.write_text(t,encoding='utf-8')
