(function(){
'use strict';
function N(s){return(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase()}
const API={'lotofacil':'lotofacil','mega-sena':'megasena','quina':'quina','dia-de-sorte':'diadesorte','lotomania':'lotomania','super-sete':'supersete','timemania':'timemania','mais-milionaria':'maismilionaria','dupla-sena':'duplasena'};
const LABEL={pares:'PARES',impares:'IMPARES',primos:'PRIMOS',fibonacci:'FIBONACCI',moldura:'MOLDURA',centro:'CENTRO',mult3:'MULT. DE 3',soma:'SOMA'};
function prime(n){if(n<2)return false;for(let i=2;i*i<=n;i++)if(n%i===0)return false;return true}
function fib(max){let s=new Set(),a=1,b=1;while(a<=max){s.add(a);[a,b]=[b,a+b]}return s}
function dims(slug){return slug==='lotofacil'?[5,5]:slug==='mega-sena'?[6,10]:slug==='quina'?[8,10]:slug==='lotomania'?[10,10]:slug==='dia-de-sorte'?[7,5]:null}
function stats(nums,slug){let fs=fib(Math.max(...nums)),d=dims(slug),m=0,c=0;if(d){let[cols,rows]=d;nums.forEach(n=>{let z=n-1,r=Math.floor(z/cols),x=z%cols;if(r===0||x===0||r===rows-1||x===cols-1)m++;else c++})}return{pares:nums.filter(n=>n%2===0).length,impares:nums.filter(n=>n%2).length,primos:nums.filter(prime).length,fibonacci:nums.filter(n=>fs.has(n)).length,moldura:d?m:null,centro:d?c:null,mult3:nums.filter(n=>n%3===0).length,soma:nums.reduce((a,b)=>a+b,0)}}
function top3(a){let c={};a.filter(v=>v!=null).forEach(v=>c[v]=(c[v]||0)+1);return Object.keys(c).map(Number).sort((x,y)=>c[y]-c[x]||x-y).slice(0,3)}
async function draw(api,n){let url='https://servicebus2.caixa.gov.br/portaldeloterias/api/'+api+(n?'/'+n:'');let r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)throw Error('HTTP '+r.status);let j=await r.json(),a=j.listaDezenas||j.dezenasSorteadasOrdemSorteio||[];return{n:+j.numero||n,nums:a.map(x=>parseInt(x,10)).filter(Number.isFinite)}}
function buttons(root){let o={};root.querySelectorAll('button').forEach(b=>{let q=N(b.textContent).trim();Object.keys(LABEL).forEach(k=>{if(q===LABEL[k]||(k==='mult3'&&q==='MULT DE 3'))o[k]=b});if(q==='FIXAS')o.fixas=b});return o}
function markPanel(root,key,vals){setTimeout(()=>{let wanted='ESCOLHA AS QUANTIDADES DE '+LABEL[key],all=[...root.querySelectorAll('div,section,fieldset')],p=all.filter(x=>N(x.innerText||x.textContent).includes(wanted)).sort((a,b)=>a.querySelectorAll('*').length-b.querySelectorAll('*').length)[0];if(!p)return;p.querySelectorAll('button').forEach(b=>{let v=parseInt((b.textContent||'').trim(),10);if(Number.isFinite(v))b.classList.toggle('thor-auto-selected',vals.includes(v))})},120)}
function bind(root,b,key){if(!b||b.dataset.thorAutoBound)return;b.dataset.thorAutoBound='1';b.addEventListener('click',()=>{let vals=(b.dataset.thorVals||'').split(',').map(Number).filter(Number.isFinite);if(vals.length)markPanel(root,key,vals)})}
function bindFixas(root,b){if(!b||b.dataset.thorFixBound)return;b.dataset.thorFixBound='1';b.addEventListener('click',()=>setTimeout(()=>{let vals=(b.dataset.thorFixas||'').split(',').map(Number),set=new Set(vals),p=[...root.querySelectorAll('div,section,fieldset')].filter(x=>N(x.innerText||x.textContent).includes('ESCOLHA AS DEZENAS FIXAS')).sort((a,c)=>a.querySelectorAll('*').length-c.querySelectorAll('*').length)[0];if(p)p.querySelectorAll('button').forEach(x=>{let n=parseInt((x.textContent||'').trim(),10);if(Number.isFinite(n))x.classList.toggle('thor-auto-selected',set.has(n))})},120))}
async function run(root){let input=root.querySelector('.thor-auto-qtd'),go=root.querySelector('.thor-auto-run'),status=root.querySelector('.thor-auto-status');if(!input||!go)return;let qtd=Math.max(1,Math.min(100,parseInt(input.value,10)||10)),slug=root.dataset.thorLottery||'lotofacil',api=API[slug];if(!api)return;go.disabled=true;go.textContent='...';if(status)status.textContent='';try{let first=await draw(api),start=first.n,rows=[],freq={};for(let i=0;i<qtd;i++){let d=i===0?first:await draw(api,start-i);if(!d.nums.length)continue;rows.push(stats(d.nums,slug));d.nums.forEach(x=>freq[x]=(freq[x]||0)+1)}if(!rows.length)throw Error('sem dados');let bs=buttons(root);Object.keys(LABEL).forEach(k=>{let vals=top3(rows.map(r=>r[k]));if(bs[k]){bs[k].dataset.thorVals=vals.join(',');bs[k].classList.add('thor-auto-ready');bind(root,bs[k],k)}});let fixed=Object.keys(freq).map(Number).sort((a,b)=>freq[b]-freq[a]||a-b).slice(0,3);if(bs.fixas){bs.fixas.dataset.thorFixas=fixed.join(',');bs.fixas.classList.add('thor-auto-ready');bindFixas(root,bs.fixas)}if(status){status.textContent='✓';status.classList.add('ok')}}catch(e){if(status){status.textContent='!';status.classList.remove('ok')}}finally{go.disabled=false;go.textContent='CALCULAR'}}
function mount(root){if(root.querySelector('.thor-auto-calc'))return;let heading=[...root.querySelectorAll('h1,h2,h3,div,strong')].filter(x=>N(x.textContent).trim()==='CONFIGURACOES AVANCADAS').sort((a,b)=>a.querySelectorAll('*').length-b.querySelectorAll('*').length)[0];if(!heading)return;let box=document.createElement('div');box.className='thor-auto-calc';box.innerHTML='<input class="thor-auto-qtd" type="number" min="1" max="100" value="10" aria-label="Concursos"><button class="thor-auto-run" type="button">CALCULAR</button><span class="thor-auto-status"></span>';heading.style.position='relative';heading.appendChild(box);box.querySelector('.thor-auto-run').addEventListener('click',e=>{e.preventDefault();e.stopPropagation();run(root)})}
function scan(){document.querySelectorAll('.thor-fechamento-luxo').forEach(mount)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(scan,250));else setTimeout(scan,250);document.addEventListener('click',()=>setTimeout(scan,80),true);new MutationObserver(()=>{clearTimeout(window.__thorAutoT);window.__thorAutoT=setTimeout(scan,150)}).observe(document.documentElement,{childList:true,subtree:true});
})();