(function(){
'use strict';
function N(s){return(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase()}
const API={'lotofacil':'lotofacil','mega-sena':'megasena','quina':'quina','dia-de-sorte':'diadesorte','lotomania':'lotomania','super-sete':'supersete','timemania':'timemania','mais-milionaria':'maismilionaria','dupla-sena':'duplasena'};
const LABEL={pares:'PARES',impares:'IMPARES',primos:'PRIMOS',fibonacci:'FIBONACCI',moldura:'MOLDURA',centro:'CENTRO',mult3:'MULT. DE 3',soma:'SOMA'};
function prime(n){if(n<2)return false;for(let i=2;i*i<=n;i++)if(n%i===0)return false;return true}
function fib(max){let s=new Set(),a=1,b=1;while(a<=max){s.add(a);[a,b]=[b,a+b]}return s}
function dims(slug){return slug==='lotofacil'?[5,5]:slug==='mega-sena'?[6,10]:slug==='quina'?[8,10]:slug==='lotomania'?[10,10]:slug==='dia-de-sorte'?[7,5]:null}
function stats(nums,slug){let fs=fib(Math.max(...nums)),d=dims(slug),m=0,c=0;if(d){let[cols,rows]=d;nums.forEach(n=>{let z=n-1,r=Math.floor(z/cols),x=z%cols;if(r===0||x===0||r===rows-1||x===cols-1)m++;else c++})}return{pares:nums.filter(n=>n%2===0).length,impares:nums.filter(n=>n%2).length,primos:nums.filter(prime).length,fibonacci:nums.filter(n=>fs.has(n)).length,moldura:d?m:null,centro:d?c:null,mult3:nums.filter(n=>n%3===0).length,soma:nums.reduce((a,b)=>a+b,0)}}
function top3(a){let c={};a.filter(v=>v!=null).forEach(v=>c[v]=(c[v]||0)+1);return Object.keys(c).map(Number).sort((x,y)=>c[y]-c[x]||x-y).slice(0,3)}
async function draw(api,n){let r=await fetch('https://servicebus2.caixa.gov.br/portaldeloterias/api/'+api+(n?'/'+n:''),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);let j=await r.json(),a=j.listaDezenas||j.dezenasSorteadasOrdemSorteio||[];return{n:+j.numero||n,nums:a.map(x=>parseInt(x,10)).filter(Number.isFinite)}}
function buttons(root){let o={};root.querySelectorAll('button').forEach(b=>{let q=N(b.textContent).trim();Object.keys(LABEL).forEach(k=>{if(q===LABEL[k]||(k==='mult3'&&q==='MULT DE 3'))o[k]=b});if(q==='FIXAS')o.fixas=b});return o}
function smallestPanel(root,needle){return[...root.querySelectorAll('div,section,fieldset')].filter(x=>N(x.innerText||x.textContent).includes(needle)).sort((a,b)=>a.querySelectorAll('*').length-b.querySelectorAll('*').length)[0]}
function markPanel(root,key,vals){setTimeout(()=>{let p=smallestPanel(root,'ESCOLHA AS QUANTIDADES DE '+LABEL[key]);if(!p)return;p.querySelectorAll('button').forEach(b=>{let v=parseInt((b.textContent||'').trim(),10);if(Number.isFinite(v))b.classList.toggle('thor-auto-selected',vals.includes(v))})},80)}
function bind(root,b,key){if(!b||b.dataset.thorAutoBound)return;b.dataset.thorAutoBound='1';b.addEventListener('click',()=>{let vals=(b.dataset.thorVals||'').split(',').map(Number).filter(Number.isFinite);if(vals.length)markPanel(root,key,vals)})}
function bindFixas(root,b){if(!b||b.dataset.thorFixBound)return;b.dataset.thorFixBound='1';b.addEventListener('click',()=>setTimeout(()=>{let set=new Set((b.dataset.thorFixas||'').split(',').map(Number));let p=smallestPanel(root,'ESCOLHA AS DEZENAS FIXAS');if(p)p.querySelectorAll('button').forEach(x=>{let n=parseInt((x.textContent||'').trim(),10);if(Number.isFinite(n))x.classList.toggle('thor-auto-selected',set.has(n))})},80))}
function localHistory(root,qtd){let arrays=[];let txt=[...root.querySelectorAll('*')].map(x=>(x.textContent||'').trim()).filter(Boolean);for(let t of txt){let ms=t.match(/(?:^|\s)(\d{1,2})(?=\s|$)/g);if(ms&&ms.length>=5){let a=ms.map(x=>parseInt(x,10)).filter(Number.isFinite);if(a.length>=5)arrays.push(a)}}let uniq=[],seen=new Set();for(let a of arrays){let k=a.join(',');if(!seen.has(k)){seen.add(k);uniq.push(a)}if(uniq.length>=qtd)break}return uniq}
async function run(root){let input=root.querySelector('.thor-auto-qtd'),go=root.querySelector('.thor-auto-run'),status=root.querySelector('.thor-auto-status');if(!input||!go)return;let qtd=Math.max(1,Math.min(100,parseInt(input.value,10)||10)),slug=root.dataset.thorLottery||'lotofacil',api=API[slug];go.disabled=true;go.textContent='...';if(status){status.textContent='';status.className='thor-auto-status'}try{let draws=[];try{let first=await draw(api),start=first.n;draws.push(first.nums);for(let i=1;i<qtd;i++){let d=await draw(api,start-i);if(d.nums.length)draws.push(d.nums)}}catch(e){draws=localHistory(root,qtd)}if(!draws.length)throw Error('sem dados');let rows=draws.map(a=>stats(a,slug)),freq={};draws.forEach(a=>a.forEach(x=>freq[x]=(freq[x]||0)+1));let bs=buttons(root);Object.keys(LABEL).forEach(k=>{let vals=top3(rows.map(r=>r[k]));if(bs[k]&&vals.length){bs[k].dataset.thorVals=vals.join(',');bs[k].classList.add('thor-auto-ready');bind(root,bs[k],k)}});let fixed=Object.keys(freq).map(Number).sort((a,b)=>freq[b]-freq[a]||a-b).slice(0,3);if(bs.fixas&&fixed.length){bs.fixas.dataset.thorFixas=fixed.join(',');bs.fixas.classList.add('thor-auto-ready');bindFixas(root,bs.fixas)}if(status){status.textContent='✓';status.classList.add('ok')}}catch(e){if(status){status.textContent='!';status.classList.add('err')}}finally{go.disabled=false;go.textContent='CALCULAR'}}
function mount(root){if(root.querySelector('.thor-auto-calc'))return;let heading=[...root.querySelectorAll('h1,h2,h3,div,strong')].filter(x=>N(x.textContent).trim()==='CONFIGURACOES AVANCADAS').sort((a,b)=>a.querySelectorAll('*').length-b.querySelectorAll('*').length)[0];if(!heading)return;let box=document.createElement('span');box.className='thor-auto-calc';box.innerHTML='<input class="thor-auto-qtd" type="number" min="1" max="100" value="10"><button class="thor-auto-run" type="button">CALCULAR</button><span class="thor-auto-status"></span>';heading.style.position='relative';heading.appendChild(box);box.querySelector('.thor-auto-run').onclick=e=>{e.preventDefault();e.stopPropagation();run(root)}}
function scan(){document.querySelectorAll('.thor-fechamento-luxo').forEach(mount)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(scan,200));else setTimeout(scan,200);document.addEventListener('click',()=>setTimeout(scan,70),true);new MutationObserver(()=>{clearTimeout(window.__thorAutoT);window.__thorAutoT=setTimeout(scan,120)}).observe(document.documentElement,{childList:true,subtree:true});
})();