(function(){
'use strict';
function N(s){return(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase()}
function designHome(){
 const root=document.getElementById('overlayListaResultados')||document;
 const tabs=root.querySelector('.home-tabs'); if(tabs){tabs.style.setProperty('margin-bottom','28px','important');tabs.style.setProperty('gap','8px','important')}
 const hero=root.querySelector('.home-hero'); if(hero){hero.style.setProperty('margin-top','18px','important');hero.style.setProperty('border-width','2px','important');hero.style.setProperty('border-radius','22px','important')}
 const nomes=['LOTOFACIL','MEGA-SENA','MEGA SENA','QUINA','DIA DE SORTE','LOTOMANIA','SUPER SETE','TIMEMANIA','+MILIONARIA','MILIONARIA','DUPLA SENA'];
 [...root.querySelectorAll('.home-hero h1,.home-hero h2,.home-hero h3,.home-hero strong,.home-hero span,.home-hero div')].forEach(e=>{let t=N(e.textContent).trim();if(nomes.includes(t)&&!e.children.length){e.classList.add('thor-home-lottery-title');e.style.setProperty('font-size','clamp(48px,12vw,82px)','important');e.style.setProperty('font-weight','950','important');e.style.setProperty('font-style','italic','important');e.style.setProperty('line-height','.9','important');e.style.setProperty('letter-spacing','-3px','important');e.style.setProperty('color','#fff','important');e.style.setProperty('text-shadow','0 9px 0 rgba(0,0,0,.38),0 0 20px rgba(255,255,255,.16)','important')}});
 const grid=[...root.querySelectorAll('.home-feature-card')][0]?.parentElement;if(grid){grid.style.setProperty('display','grid','important');grid.style.setProperty('grid-template-columns','repeat(2,minmax(0,1fr))','important');grid.style.setProperty('gap','8px','important')}
}
function homeTendencia(){const old=document.getElementById('homePremiumCardTendencia');if(old)old.style.setProperty('display','none','important');const cards=[...document.querySelectorAll('.home-feature-card')];if(!cards.length)return;let c=document.querySelector('.home-feature-card.thor-tendencia-real');if(!c){const base=cards[0],grid=base.parentElement;c=base.cloneNode(true);c.classList.add('thor-tendencia-real');c.removeAttribute('id');c.setAttribute('data-home-target','btnTendenciaAtalho');c.removeAttribute('onclick');const strong=c.querySelector('strong'),small=c.querySelector('small'),ico=c.querySelector('.hfc-icon');if(strong)strong.textContent='Tendência';if(small)small.textContent='Dezenas em alta e queda';if(ico)ico.textContent='↗';c.style.setProperty('--fc','#6d7fa8');grid.appendChild(c)}}
function moveFechamento(){const tend=document.querySelector('.home-feature-card.thor-tendencia-real');if(!tend)return;const grid=tend.parentElement;if(!grid)return;let card=document.querySelector('.thor-fechamento-abaixo-tendencia');if(!card){const a=[...document.querySelectorAll('div,section,button,a')].filter(e=>{const t=N(e.innerText||e.textContent);return t.includes('FECHAMENTO PERSONALIZADO')&&t.includes('MONTE SUAS DEZENAS')&&t.includes('GERAR')&&!t.includes('ULTIMO SORTEIO')});a.sort((x,y)=>x.querySelectorAll('*').length-y.querySelectorAll('*').length);card=a[0]}if(!card||card===grid||card.contains(grid))return;if(card.parentElement!==grid)grid.appendChild(card);card.classList.add('thor-fechamento-abaixo-tendencia');['height','min-height','max-height'].forEach(x=>card.style.setProperty(x,'1.7cm','important'));card.style.setProperty('width','auto','important');card.style.setProperty('margin','0','important');card.style.setProperty('box-sizing','border-box','important');let g=[...card.querySelectorAll('button,a')].find(b=>N(b.textContent).includes('GERAR'));if(g)g.style.setProperty('display','none','important')}
function scan(){homeTendencia();moveFechamento();designHome()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(scan,200));else setTimeout(scan,200);document.addEventListener('click',()=>setTimeout(scan,80),true);new MutationObserver(()=>{clearTimeout(window.__thorDesignT);window.__thorDesignT=setTimeout(scan,100)}).observe(document.documentElement,{childList:true,subtree:true});
})();