(function(){'use strict';
const MIN={megasena:4,lotofacil:11,quina:2,diadesorte:4,lotomania:15,supersete:3,timemania:3,duplasena:3};
function slug(){const a=document.querySelector('#thorJogosLoterias .thorJogoLoteria.ativa');if(!a)return'';const t=(a.textContent||'').trim().toLowerCase();return {'mega-sena':'megasena','lotofácil':'lotofacil','quina':'quina','dia de sorte':'diadesorte','lotomania':'lotomania','super sete':'supersete','timemania':'timemania','dupla sena':'duplasena'}[t]||''}
function banco(){try{return JSON.parse(localStorage.getItem('thor_meus_jogos')||'{}')||{}}catch(_){return{}}}
function resultado(){return [...document.querySelectorAll('#thorJogosResultado .jr-bola')].map(e=>String(e.textContent||'').trim().padStart(2,'0'))}
function conferir(){const s=slug(),res=resultado(),lista=(banco()[s]||[]),cards=[...document.querySelectorAll('#thorMeusJogosLista .mj-card')];if(!s||!res.length||!cards.length)return;const set=new Set(res);cards.forEach((card,i)=>{const x=lista[i]||{},nums=x.numeros||x.dezenas||x.jogo||[];let ac=nums.reduce((n,v)=>n+(set.has(String(v).trim().padStart(2,'0'))?1:0),0);card.classList.remove('thor-premiado');let tag=card.querySelector('.thor-pontos');if(!tag){tag=document.createElement('span');tag.className='thor-pontos';const info=card.querySelector('.mj-info');if(info)info.appendChild(tag)}tag.textContent=' · '+ac+' ACERTO'+(ac===1?'':'S');if(ac>=(MIN[s]||999)){card.classList.add('thor-premiado');tag.textContent+=' · PREMIADO'}})}
function css(){if(document.getElementById('thorPremios8Css'))return;const st=document.createElement('style');st.id='thorPremios8Css';st.textContent='.thor-pontos{font-weight:1000;color:#17324a}.mj-card.thor-premiado{border:3px solid #f3b300!important;background:linear-gradient(180deg,#fffbdc,#fff2a8)!important;box-shadow:0 0 0 2px #0b9d45,0 0 14px rgba(255,190,0,.8)!important}.mj-card.thor-premiado .thor-pontos{display:inline-block;margin-left:5px;padding:2px 6px;border-radius:10px;background:#087f35;color:#fff!important;text-shadow:0 1px 1px #003b18}';document.head.appendChild(st)}
function ligar(){css();document.addEventListener('click',e=>{if(e.target&&e.target.id==='thorMeusJogos')setTimeout(conferir,60);if(e.target&&e.target.classList&&e.target.classList.contains('thorJogoLoteria'))setTimeout(conferir,600)});new MutationObserver(()=>setTimeout(conferir,30)).observe(document.documentElement,{subtree:true,childList:true,characterData:true});setTimeout(conferir,800)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ligar,{once:true});else ligar();window.thorConferirPremios=conferir;
})();