// THOR LOTERIAS - Service Worker
// Base 142 preservada - força menu azul metálico 3D animado
const CACHE_NAME='thor-loterias-base-142-menu-metalico-3d-5';
const CORE=['./','./index.html','./app-main.html','./gerador.html','./gerador-palpites.js','./analysis-neon.css','./fechamento-personalizado-luxo.css','./home-topo-thor.css','./home-update-fix.js','./menu-lateral-claro-laranja.css','./filtros-auto.js','./manifest.json','./icon-192.png','./icon-512.png','./icon-512-maskable.png'];
const PALPITES_CARD='<button class="home-feature-card" style="--fc:#d41948" data-home-target="btnTendenciaAtalho"><span class="hfc-icon">◎</span><span><strong>Palpites</strong><small>Sugestões inteligentes</small></span></button>';
const CALC_CARD='<button class="home-feature-card" style="--fc:#e98a00" data-home-target="btnSimularAtalho"><span class="hfc-icon">▤</span><span><strong>Calculadora</strong><small>Probabilidades e estimativas</small></span></button>';
const ESCOLHA_CARD='<button class="home-feature-card" id="btnEscolhaPraMim" style="--fc:#18a96b" type="button"><span class="hfc-icon">★</span><span><strong>Escolha pra mim</strong><small>Sugestão automática</small></span></button>';
const MENU_CSS=`<style id="thorMenuMetalico3DForcado">#homeSideNav{align-items:center!important}#homeSideNav .hs-menu,#homeSideNav .hs-item{width:88%!important;min-height:38px!important;height:38px!important;padding:0 8px!important;margin-left:auto!important;margin-right:auto!important;margin-bottom:8px!important;box-sizing:border-box!important;display:flex!important;align-items:center!important;justify-content:center!important;text-align:center!important;background:linear-gradient(180deg,#c8edff 0%,#76c5ec 30%,#3f9dce 58%,#2679ad 82%,#175d8d 100%)!important;border:2px solid #ff8a00!important;border-radius:6px!important;color:#fff!important;font-size:10px!important;font-weight:800!important;text-shadow:0 1px 2px rgba(0,52,88,.95)!important;box-shadow:inset 0 3px 3px rgba(255,255,255,.92),inset 0 -4px 6px rgba(0,54,94,.52),0 3px 0 #a84b00,0 5px 8px rgba(0,0,0,.42),0 0 5px #ffb13b,0 0 11px rgba(255,119,0,.95)!important;transform:translateY(0) scale(1)!important;transition:transform .10s ease,box-shadow .10s ease,filter .10s ease!important;animation:thorMenuEntrada .32s ease-out both!important}#homeSideNav .hs-item:nth-child(2){animation-delay:.03s!important}#homeSideNav .hs-item:nth-child(3){animation-delay:.06s!important}#homeSideNav .hs-item:nth-child(4){animation-delay:.09s!important}#homeSideNav .hs-item:nth-child(5){animation-delay:.12s!important}#homeSideNav .hs-item:nth-child(6){animation-delay:.15s!important}#homeSideNav .hs-item:nth-child(7){animation-delay:.18s!important}#homeSideNav .hs-item:nth-child(8){animation-delay:.21s!important}#homeSideNav .hs-menu{font-size:0!important}#homeSideNav .hs-menu::after{content:'MENU';font-size:10px!important;font-weight:800!important;color:#fff!important;width:100%!important;text-align:center!important}#homeSideNav .hs-item:active,#homeSideNav .hs-menu:active{transform:translateY(4px) scale(.985)!important;filter:brightness(.88)!important;box-shadow:inset 0 5px 9px rgba(0,42,75,.72),inset 0 -1px 2px rgba(255,255,255,.38),0 1px 0 #8d3e00,0 1px 3px rgba(0,0,0,.35),0 0 5px #ffb13b,0 0 9px rgba(255,119,0,.82)!important}@keyframes thorMenuEntrada{0%{transform:translateY(-5px) scale(.97);filter:brightness(1.28)}60%{transform:translateY(2px) scale(1.01)}100%{transform:translateY(0) scale(1);filter:brightness(1)}}</style>`;
function prepararHome(html){html=html.replace(PALPITES_CARD,'');if(!html.includes('id="btnEscolhaPraMim"'))html=html.replace(CALC_CARD,CALC_CARD+'\n'+ESCOLHA_CARD);if(!html.includes('src="./gerador-palpites.js'))html=html.replace('</body>','<script src="./gerador-palpites.js?v=escolha-gerador-sem-piscar-1"><\/script></body>');html=html.replace('</head>',MENU_CSS+'<style id="thorSemPiscar">#overlayListaResultados{visibility:hidden!important}html.thor-home-pronta #overlayListaResultados{visibility:visible!important}</style></head>');const pronto=`<script>(function(){function ligarEscolha(){var b=document.getElementById('btnEscolhaPraMim');if(!b)return;b.removeAttribute('data-home-target');b.onclick=function(e){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();location.href='./gerador.html?v=escolha-gerador-sem-piscar-1'}}function revelar(){var h=document.getElementById('homeHero');if(!h)return false;var t=(h.textContent||'').trim();if((/Concurso/i.test(t)&&!/Buscando concurso/i.test(t))||h.querySelector('.hh-ball')){document.documentElement.classList.add('thor-home-pronta');return true}return false}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ligarEscolha,{once:true});else ligarEscolha();if(!revelar()){var o=new MutationObserver(function(){ligarEscolha();if(revelar())o.disconnect()});o.observe(document.documentElement,{childList:true,subtree:true,characterData:true});setTimeout(function(){document.documentElement.classList.add('thor-home-pronta');o.disconnect()},8000)}})();<\/script>`;return html.replace('</body>',pronto+'</body>')}
async function respostaAtualizada(req){const fresh=await fetch(req,{cache:'no-store'});if(!fresh||!fresh.ok)return fresh;const url=new URL(req.url);if(url.pathname.endsWith('/app-main.html')){const html=prepararHome(await fresh.text()),headers=new Headers(fresh.headers);headers.set('content-type','text/html; charset=utf-8');headers.set('cache-control','no-store, no-cache, must-revalidate');return new Response(html,{status:fresh.status,statusText:fresh.statusText,headers})}return fresh}
self.addEventListener('install',event=>{event.waitUntil((async()=>{const cache=await caches.open(CACHE_NAME);for(const url of CORE){try{const sep=url.includes('?')?'&':'?';const req=new Request(url+sep+'_refresh=menu-metalico-3d-5',{cache:'no-store'}),res=await respostaAtualizada(req);if(res&&res.ok)await cache.put(url,res.clone())}catch(_){}}})());self.skipWaiting()});
self.addEventListener('message',event=>{if(event.data&&event.data.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)));await self.clients.claim();const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});clients.forEach(c=>c.postMessage({type:'THOR_UPDATED',version:'142',refresh:'menu-metalico-3d-5'}))})())});
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;event.respondWith((async()=>{try{const fresh=await respostaAtualizada(req);if(fresh&&fresh.ok){const cache=await caches.open(CACHE_NAME);cache.put(req,fresh.clone())}return fresh}catch(_){const cached=await caches.match(req);if(cached)return cached;if(req.mode==='navigate')return await caches.match('./index.html');return Response.error()}})())});